### ISSUE TITLE
No live reloading

### ISSUE THREAD

**Issue by JimiJonJimbo** [domix/spring-boot-starter-jade4j#3]
When I make changes to my .jade files, I have to restart my project in order to see the changes (just refreshing the page in the browser doesn't work). I have set spring.jade4j.caching to false but it doesn't help. Is live reloading broken?

Thanks!

**Comment by domix** [comment]
Which building tool are you using?

**Comment by JimiJonJimbo** [comment]
Gradle.

**Comment by domix** [comment]
In order to reload the changes to jade templates you need some mechanism to  `watch` for the changes.

The [showcase](https://github.com/domix/spring-boot-starter-jade4j-showcase)  is using the [Gradle Watch plugin](https://github.com/bluepapa32/gradle-watch-plugin) 

- Please checkout the [showcase code](https://github.com/domix/spring-boot-starter-jade4j-showcase) 
- in a terminal in the directory where you checkout the code, execute `gradle bootRun`
- open a new terminal and execute `gradle watch`
- Now you can change the jade templates and then see the updates in the browser.

The dynamic reloading of jade templates is out of scope of this `SpringBoot starter`

**Comment by JimiJonJimbo** [comment]
gradle watch was the missing step for me. Thanks!
